<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net11.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <PackAsTool>true</PackAsTool>
    <ToolCommandName>adr</ToolCommandName>
    <PackageId>AdrTool</PackageId>
    <Version>0.2.0</Version>
    <Description>A CLI tool for creating and managing Architecture Decision Records (ADRs) from a customizable template.</Description>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <Authors>versussun</Authors>
    <PackageLicenseExpression>0BSD</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/versussun/AdrTool.git</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="templates/**/*" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <None Include="../README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
